[package]
name = "wateor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.20"
anyhow = "1.0.40"
tar = "0.4.35"
bzip2 = "0.4.2"
directories = "3.0.2"
chrono = "0.4.19"
